---
#services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
      - '8083:8083'
    volumes:
      - influxdb-storage:/var/lib/influxdb
 #   restart:
  #    always 
    environment:
      - INFLUXDB_DB=db0
  grafana:
    image: grafana/grafana 
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana    
    links:
       - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
   # restart:
     # always
 # volumes:
 #   influxdb-storage:
 #   grafana-storage:
